# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'withinTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for withinTest
pod 'Alamofire', '~> 5.0.0-beta.5'

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Kingfisher'
  pod 'SVGKit'
  pod 'SnapKit'
  pod 'Then'
  pod 'ReactorKit'
end
