# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewHomework' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewHomework

  pod 'ReactorKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SVGKit'
  pod 'SnapKit'
  pod 'Then'
  
end
